certificat_certificats:
    resource: "@CertificatBundle/Controller/CertificatsController.php"
    type:     annotation

certificats:
    resource: "@CertificatBundle/Resources/config/routing.yml"
    prefix:   /certificats


certificat:
    resource: "@CertificatBundle/Resources/config/routing.yml"
    prefix:   /



message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /message


reclamation1_reclamation:
    resource: "@Reclamation1Bundle/Controller/ReclamationController.php"
    type:     annotation

reclamation:
    resource: "@Reclamation1Bundle/Resources/config/routing.yml"
    prefix : /reclamation

reclamation1:
    resource: "@Reclamation1Bundle/Resources/config/routing.yml"
    prefix:   /


offre_offres:
    resource: "@OffreBundle/Controller/OffresController.php"
    type:     annotation


user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

offre:
    resource: "@OffreBundle/Resources/config/routing.yml"
    prefix:   /offre

app:
    resource: '@AppBundle/Controller/'
    type: annotation

index:
    path:     /index
    defaults: { _controller: AppBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

