interviews_homepage:
    path:     /
    defaults: { _controller: InterviewsBundle:Default:index }

interview_index:
    path:     /
    defaults: { _controller: "InterviewsBundle:Interview:index" }
    methods:  GET

interview_show:
    path:     /{refEnt}/show
    defaults: { _controller: "InterviewsBundle:Interview:show" }
    methods:  GET

interview_new:
    path:     /new
    defaults: { _controller: "InterviewsBundle:Interview:new" }
    methods:  [GET, POST]

interview_edit:
    path:     /{refEnt}/edit
    defaults: { _controller: "InterviewsBundle:Interview:edit" }
    methods:  [GET, POST]

interview_delete:
    path:     /{refEnt}/delete
    defaults: { _controller: "InterviewsBundle:Interview:delete" }
    methods:  DELETE

affiches_offres:
    path:     /affichoffres_ent
    defaults: { _controller: "InterviewsBundle:Interview:affichoffres_ent" }
    methods:  GET

ajouter_interview:
    path:     /{offre_id}/ajout
    defaults: { _controller: "InterviewsBundle:Interview:ajouter_interview"}
    methods:  [GET, POST]

afficherInterview:
    path:     /afficherInterview
    defaults: { _controller: "InterviewsBundle:Interview:afficherInterview" }
    methods:  GET

modifier_interview:
    path:     /{refEnt}/editinterview
    defaults: { _controller: "InterviewsBundle:Interview:modifierInterview" }
    methods:  [GET, POST]

delete_interview:
    path:     /deleteInteview/{refEnt}
    defaults: { _controller: "InterviewsBundle:Interview:deleteInterview" }

add_eval:
    path:     /add_eval/{refEnt}
    defaults: { _controller: "InterviewsBundle:Interview:add_eval" }

show_evalUnique:
    path:     /show_evalUnique/{refEnt}
    defaults: { _controller: "InterviewsBundle:Interview:show_evalUnique" }

show_eval:
    path:     /show_eval
    defaults: { _controller: "InterviewsBundle:Interview:show_eval" }

edit_eval:
    path:     /edit_eval/{refEntretien}
    defaults: { _controller: "InterviewsBundle:Interview:edit_eval"}

delete_eval:
    path:     /delete_eval/{refEntretien}
    defaults: { _controller: "InterviewsBundle:Interview:delete_eval" }


refuserDemandeinterview:
    path:     /refuserDemandeinterview/{offre_id}
    defaults: { _controller: "InterviewsBundle:Interview:refuserDemandeinterview"}

ajax_search:
    path:     /search
    defaults: { _controller: "InterviewsBundle:Interview:search" }

ajax_search_eval:
    path:     /searcheval
    defaults: { _controller: "InterviewsBundle:Interview:search_eval" }

ajax_search_c:
    path:     /searchC
    defaults: { _controller: "InterviewsBundle:Interview:searchC" }


