user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

redirect_login:
    path: /redirect
    defaults: { _controller: UserBundle:Default:redirect}

mon_profil:
    path: /monprofil
    defaults: { _controller: UserBundle:Default:monprofil}
