formations_index:
    path:     /
    defaults: { _controller: "FormationBundle:Formations:index" }
    methods:  GET

formations_index_all:
    path:     /all
    defaults: { _controller: "FormationBundle:Formations:indexall" }
    methods:  GET

formations_show:
    path:     /{ref}/show
    defaults: { _controller: "FormationBundle:Formations:show" }
    methods:  GET

formations_new:
    path:     /new
    defaults: { _controller: "FormationBundle:Formations:new" }
    methods:  [GET, POST]

formations_edit:
    path:     /{ref}/edit
    defaults: { _controller: "FormationBundle:Formations:edit" }
    methods:  [GET, POST]

formations_delete:
    path:     /{ref}/delete
    defaults: { _controller: "FormationBundle:Formations:delete" }
    methods:  DELETE
