formations_affich_all:
  path:     /allformations
  defaults: { _controller: "FormationBundle:Inscriptions:affichallFormations" }
  methods:  GET

formations_show_all:
  path:     /{ref}/showformation
  defaults: { _controller: "FormationBundle:Inscriptions:showallFormations" }
  methods:  [GET, POST]


ajout_filtre:
  path:     /{domaine}/filtre
  defaults: { _controller: "FormationBundle:Inscriptions:domaine" }
  methods:  GET

inscrip_affich_all:
  path:     /allinscriptions
  defaults: { _controller: "FormationBundle:Inscriptions:affichInscri" }
  methods:  GET

etat_accepte:
  path:     /{id}/accepte
  defaults: { _controller: "FormationBundle:Inscriptions:etataccepte"}
  methods:  [GET, POST]

etat_refuse:
  path:     /{id}/refusee
  defaults: { _controller: "FormationBundle:Inscriptions:etatrefuse"}
  methods:  [GET, POST]


formation_smsfromadmin:
  path:     /smssend
  defaults: { _controller: "FormationBundle:Inscriptions:sendsms" }
  methods:  GET