offre_offres:
    resource: "@OffreBundle/Resources/config/routing/offres.php"
    prefix:   /offres

offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Default:index }

ajouter_offre:
    path:     /ajouteroffre
    defaults: { _controller: OffreBundle:Offres:new }

read_offre:
    path:     /listoffre
    defaults: { _controller: OffreBundle:Offres:index }

read_offre_user:
    path:     /listoffre
    defaults: { _controller: OffreBundle:Offres:index }

mes_offre:
    path:     /mesoffres
    defaults: { _controller: OffreBundle:Offres:mesOffres }

modifier_offre:
    path:     /modifieroffre/{id}
    defaults: { _controller: OffreBundle:Offres:edit}

supprimer_offre:
    path:     /supprimeroffre/{id}
    defaults: { _controller: OffreBundle:Offres:delete }

consulter_offre:
    path:     /consulteroffre/{id}
    defaults: { _controller: OffreBundle:Offres:consulterOffre }

postuler_offre:
    path:     /postuleroffre/{id}/{match}
    defaults: { _controller: OffreBundle:Applications:postuler }

mes_condidatures:
    path:     /mescandidatures
    defaults: { _controller: OffreBundle:Offres:mescandidatures}

supprimer_application:
    path:     /supprimer/{id}
    defaults: { _controller: OffreBundle:Applications:delete}