offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Default:index }

ajouter_homepage:
    path:     /ajouter
    defaults: { _controller: OffreBundle:Default:ajouter }

read_homepage:
    path:     /read
    defaults: { _controller: OffreBundle:Default:read }
